### ISSUE TITLE
How to annotate set<i64> and map<x, i64> in thrift definition files?

### ISSUE THREAD

**Issue by lxe** [thriftrw/thriftrw-node#159]
What's the proper way to annotate the `map<string, i64>` and `set<i64>` types? Doing

```
map<string, i64> (js.type = "Long") 
```

generates this error:

```
.../node_modules/thriftrw/map.js:41
        throw errors.UnexpectedMapTypeAnnotation({
        ^

ThriftUnexpectedMapTypeAnnotationError: unexpected map js.type annotation "Long"
    at Object.createError [as UnexpectedMapTypeAnnotation] (.../node_modules/error/typed.js:31:22)
```

while
```
set<i64> (js.type = "Long")
```

generates this error:

```
assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: set must have js.type of object or array (default)
    at new ThriftSet (/.../node_modules/thriftrw/set.js:56:16)
```

**Comment by abhinav** [comment]
You should be able to do,

    map<string, i64 (js.type = "Long")>
    set<i64 (js.type = "Long")>

Or better yet, declare a typedef and use that.

    typedef i64 (js.type = "Long") Long

Then,

    map<string, Long>
    set<Long>

**Comment by lxe** [comment]
Thank you @abhinav. This worked
