### ISSUE TITLE
Service arguments parse error

### ISSUE THREAD

**Issue by lushijie** [thriftrw/thriftrw-node#163]
```
// m21.thrift file
struct Code {
  1: string abc
}

// m2.thrift file
include 'm21.thrift'
service Test {
  void ping(m21.Code a);
}
```

parse error message: 

```
 assert(def.isResult || def.id.value > 0,
                                  ^

TypeError: Cannot read property 'value' of null
    at new ThriftField (/Users/lushijie/github/thrift-json/node_modules/thriftrw/struct.js:40:35)
    at ThriftStruct.compile (/Users/lushijie/github/thrift-json/node_modules/thriftrw/struct.js:122:21)
    at Thrift.compileStruct (/Users/lushijie/github/thrift-json/node_modules/thriftrw/thrift.js:307:11)
```

**Comment by kriskowal** [comment]
Thank you for submitting! We should make this error more informative. I believe you need to add a field number to the ping argument. `ping(1: m21.Code a)`.
